sudo: required
language: rust
addons:
  apt:
    packages:
      - libssl-dev
cache:
  directories:
    - $HOME/.cargo
before_cache:
  - cargo install cargo-tarpaulin
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - rm -rf $HOME/.cargo/registry
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo fmt -- --check
after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
